DROP TABLE Job cascade;
DROP TABLE State cascade;
DROP TABLE JobParameter cascade;
DROP TABLE JobQueue cascade;
DROP TABLE Server cascade;
DROP TABLE List cascade;
DROP TABLE Set cascade;
DROP TABLE Counter cascade;
DROP TABLE Hash cascade;
DROP TABLE Schema cascade;
drop table lock;
