INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (1, NULL, 1, 'Lower Mainland', 1, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (2, NULL, 2, 'Vancouver Island', 1, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (3, NULL, 3, 'Rocky Mountain', 2, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (4, NULL, 4, 'West Kootenay', 2, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (5, NULL, 5, 'Okanagan-Shuswap', 2, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (6, NULL, 6, 'Thompson-Nicola', 2, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (7, NULL, 7, 'Cariboo', 2, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (8, NULL, 8, 'Peace', 3, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (9, NULL, 9, 'Fort George', 3, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (10, NULL, 10, 'Bulkley-Stikine', 3, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (11, NULL, 11, 'Skeena', 3, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (12, NULL, 99, 'NON-BC', 4, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_DISTRICT"
("DISTRICT_ID", "END_DATE", "MINISTRY_DISTRICT_ID", "NAME", "REGION_ID", "START_DATE", "DISTRICT_NUMBER", "CREATE_TIMESTAMP", "CREATE_USERID", 
 "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (13, NULL, 999, 'Unknown', 5, '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');


