INSERT INTO public."HET_REGION"
("REGION_ID", "END_DATE", "MINISTRY_REGION_ID", "NAME", "START_DATE", "REGION_NUMBER", 
 "CREATE_TIMESTAMP", "CREATE_USERID", "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (1, NULL, 1, 'South Coast', '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_REGION"
("REGION_ID", "END_DATE", "MINISTRY_REGION_ID", "NAME", "START_DATE", "REGION_NUMBER", 
 "CREATE_TIMESTAMP", "CREATE_USERID", "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (2, NULL, 2, 'Southern Interior', '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_REGION"
("REGION_ID", "END_DATE", "MINISTRY_REGION_ID", "NAME", "START_DATE", "REGION_NUMBER", 
 "CREATE_TIMESTAMP", "CREATE_USERID", "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (3, NULL, 3, 'Northern', '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_REGION"
("REGION_ID", "END_DATE", "MINISTRY_REGION_ID", "NAME", "START_DATE", "REGION_NUMBER", 
 "CREATE_TIMESTAMP", "CREATE_USERID", "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (4, NULL, 99, 'NON-BC', '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');

INSERT INTO public."HET_REGION"
("REGION_ID", "END_DATE", "MINISTRY_REGION_ID", "NAME", "START_DATE", "REGION_NUMBER", 
 "CREATE_TIMESTAMP", "CREATE_USERID", "LAST_UPDATE_TIMESTAMP", "LAST_UPDATE_USERID")
VALUES (5, NULL, 999, 'Unknown', '2009-01-01', NULL, current_timestamp, 'plitton', current_timestamp, 'plitton');