--- Master script for HETS HIST tables and Triggers
\set ON_ERROR_STOP 1
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_EQUIPMENT_ATTACHMENT_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_EQUIPMENT_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_NOTE_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_RENTAL_AGREEMENT_CONDITION_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_RENTAL_AGREEMENT_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_RENTAL_AGREEMENT_RATE_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_RENTAL_REQUEST_ROTATION_LIST_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_SEQ_DDL/HET_TIME_RECORD_HIST_seq.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_EQUIPMENT_ATTACHMENT_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_EQUIPMENT_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_NOTE_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_RENTAL_AGREEMENT_CONDITION_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_RENTAL_AGREEMENT_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_RENTAL_AGREEMENT_RATE_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_RENTAL_REQUEST_ROTATION_LIST_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_DDL/HET_TIME_RECORD_HIST.sql
\i C:/Data/Hets/HETS_v3.0/TABLE_HIST_PRIMARY_KEY/primary_key_code.sql
\i C:/Data/Hets/HETS_v3.0/BEFORE_TRIGGER/TriggerFunctions/het_validate_init_audit_cols.sql
\i C:/Data/Hets/HETS_v3.0/BEFORE_TRIGGER/Triggers/all_br_iu_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_eqpatt_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_eqp_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_note_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_rntagc_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_rntagr_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_rntag_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_rntrrl_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/TriggerFunctions/het_timrec_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_eqpatt_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_eqp_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_note_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_rntagc_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_rntagr_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_rntag_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_rntrrl_ar_iud_tr.sql
\i C:/Data/Hets/HETS_v3.0/AFTER_TRIGGER/Triggers/het_timrec_ar_iud_tr.sql