stage('ZAP Security Scan') {
    node('zap') {
            //the checkout is mandatory, otherwise functional test would fail
            echo "checking out source"
            echo "Build: ${BUILD_ID}"
            checkout scm
            dir('zap') {
                def retVal = sh returnStatus: true, script: '/zap/zap-x.sh -last_scan_report /home/jenkins/workspace/tran-hets-tools-zap-pipeline/zap/index.html -session /home/jenkins/workspace/workspace/tran-hets-tools-zap-pipeline/zap/HETS -cmd'
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/home/jenkins/workspace/workspace/tran-hets-tools-zap-pipeline/zap', reportFiles: 'index.html', reportName: 'ZAP Scan', reportTitles: 'ZAP Scan - Build: ${BUILD_ID}'])
                echo "Return value is: ${retVal}"
            }
    }
}
