podTemplate(label: 'owasp-zap', name: 'owasp-zap', serviceAccount: 'jenkins', cloud: 'openshift', containers: [
  containerTemplate(
    name: 'jnlp',
    image: '172.50.0.2:5000/openshift/jenkins-slave-zap',
    resourceRequestCpu: '500m',
    resourceLimitCpu: '1000m',
    resourceRequestMemory: '3Gi',
    resourceLimitMemory: '4Gi',
    workingDir: '/home/jenkins',
    command: '',
    args: '${computer.jnlpmac} ${computer.name}'
  )
]) {
    stage('ZAP Security Scan') {
        node('owasp-zap') {
                //the checkout is mandatory, otherwise functional test would fail
                echo "checking out source"
                echo "Build: ${BUILD_ID}"
                checkout scm
                dir('zap') {
                    def retVal = sh returnStatus: true, script: '/zap/zap-x.sh -last_scan_report /home/jenkins/workspace/tran-hets-tools-zap-pipeline/zap/index.html -session /home/jenkins/workspace/tran-hets-tools-zap-pipeline/zap/HETS -cmd'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/home/jenkins/workspace/tran-hets-tools-zap-pipeline/zap', reportFiles: 'index.html', reportName: 'ZAP Scan', reportTitles: 'ZAP Scan Report'])
                    echo "Return value is: ${retVal}"
                }
        }
    }
}    
