import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faCalendarAlt as faCalendarAltRegular, 
  faCheckCircle as faCheckCircleRegular,
  faEdit as faEditRegular, 
  faFolderOpen as faFolderOpenRegular, 
  faStar as faStarRegular, 
  faTimesCircle as faTimesCircleRegular, 
  faTrashAlt as faTrashAltRegular, 
} from '@fortawesome/free-regular-svg-icons';

import { 
  faArrowLeft, 
  faAsterisk, 
  faCalendarAlt, 
  faCheck, 
  faCheckCircle, 
  faCheckSquare, 
  faDownload, 
  faEdit, 
  faEnvelope, 
  faExclamationCircle, 
  faFolderOpen, 
  faFileUpload, 
  faMinus, 
  faPencilAlt, 
  faPlus, 
  faPrint, 
  faSortAmountDown, 
  faSortAmountDownAlt, 
  faStar, 
  faSyncAlt, 
  faTimes, 
  faTimesCircle, 
  faTrashAlt, 
  faUser,
} from '@fortawesome/free-solid-svg-icons';

export const registerFaIcons = () => {
  library.add(
    faCheckCircle, 
    faCheckCircleRegular,
    faTimesCircle,
    faTimesCircleRegular,
    faCalendarAlt,
    faCalendarAltRegular,
    faTrashAlt,
    faTrashAltRegular,
    faEdit,
    faEditRegular,
    faPencilAlt,
    faStar,
    faStarRegular,
    faTimes,
    faFolderOpen,
    faFolderOpenRegular,
    faFileUpload,
    faSyncAlt,
    faPrint,
    faArrowLeft,
    faSortAmountDown,
    faSortAmountDownAlt,
    faPlus,
    faCheck,
    faCheckSquare,
    faExclamationCircle,
    faUser,
    faAsterisk,
    faEnvelope,
    faMinus,
    faDownload,
  );
};
