-- FUNCTION: public.het_eqp_ar_iud_tr()

DROP FUNCTION IF EXISTS public.het_eqp_ar_iud_tr() CASCADE;

CREATE FUNCTION public.het_eqp_ar_iud_tr()
    RETURNS trigger
    LANGUAGE 'plpgsql'
  
AS $BODY$

	DECLARE
        l_current_timestamp timestamp;
	BEGIN
        l_current_timestamp := current_timestamp;
    	IF(TG_OP = 'INSERT') THEN
        	INSERT INTO public."HET_EQUIPMENT_HIST"
            ("EQUIPMENT_HIST_ID",
             "EQUIPMENT_ID",
             "EFFECTIVE_DATE",
             "END_DATE",
             "APPROVED_DATE",
             "ARCHIVE_DATE",
             "ARCHIVE_REASON",
             "BLOCK_NUMBER",
             "ARCHIVE_CODE",
             "DISTRICT_EQUIPMENT_TYPE_ID",
             "EQUIPMENT_CODE",
             "LOCAL_AREA_ID",
             "MAKE",
             "MODEL",
             "OPERATOR",
             "OWNER_ID",
             "PAY_RATE",
             "RECEIVED_DATE",
             "REFUSE_RATE",
             "LICENCE_PLATE",
             "SENIORITY",
             "SERIAL_NUMBER",
             "SIZE",
             "STATUS",
             "TO_DATE",
             "YEARS_OF_SERVICE",
             "SERVICE_HOURS_LAST_YEAR",
             "SERVICE_HOURS_THREE_YEARS_AGO",
             "SERVICE_HOURS_TWO_YEARS_AGO",
             "YEAR",
             "LAST_VERIFIED_DATE",
             "INFORMATION_UPDATE_NEEDED_REASON",
             "IS_INFORMATION_UPDATE_NEEDED",
             "SENIORITY_EFFECTIVE_DATE",
             "IS_SENIORITY_OVERRIDDEN",
             "SENIORITY_OVERRIDE_REASON",
             "NUMBER_IN_BLOCK",
             "DB_CREATE_TIMESTAMP",
             "DB_CREATE_USER_ID",
             "DB_LAST_UPDATE_TIMESTAMP",
             "DB_LAST_UPDATE_USER_ID",
             "APP_CREATE_TIMESTAMP",
             "APP_CREATE_USERID",
             "APP_CREATE_USER_GUID",
             "APP_CREATE_USER_DIRECTORY",
             "APP_LAST_UPDATE_TIMESTAMP",
             "APP_LAST_UPDATE_USERID",
             "APP_LAST_UPDATE_USER_GUID",
             "APP_LAST_UPDATE_USER_DIRECTORY",
			 "TYPE",
			 "STATUS_COMMENT",
			 "LEGAL_CAPACITY",
			 "LICENCED_GVW",
			 "PUP_LEGAL_CAPACITY",
             "CONCURRENCY_CONTROL_NUMBER"
			 
            )
            VALUES( 
              nextval('"HET_EQUIPMENT_HIST_ID_seq"'::regclass),
              NEW."EQUIPMENT_ID",
              l_current_timestamp,
              NULL,
              NEW."APPROVED_DATE",
              NEW."ARCHIVE_DATE",
              NEW."ARCHIVE_REASON",
              NEW."BLOCK_NUMBER",
              NEW."ARCHIVE_CODE",
              NEW."DISTRICT_EQUIPMENT_TYPE_ID",
              NEW."EQUIPMENT_CODE",
              NEW."LOCAL_AREA_ID",
              NEW."MAKE",
              NEW."MODEL",
              NEW."OPERATOR",
              NEW."OWNER_ID",
              NEW."PAY_RATE",
              NEW."RECEIVED_DATE",
              NEW."REFUSE_RATE",
              NEW."LICENCE_PLATE",
              NEW."SENIORITY",
              NEW."SERIAL_NUMBER",
              NEW."SIZE",
              NEW."STATUS",
              NEW."TO_DATE",
              NEW."YEARS_OF_SERVICE",
              NEW."SERVICE_HOURS_LAST_YEAR",
              NEW."SERVICE_HOURS_THREE_YEARS_AGO",
              NEW."SERVICE_HOURS_TWO_YEARS_AGO",
              NEW."YEAR",
              NEW."LAST_VERIFIED_DATE",
              NEW."INFORMATION_UPDATE_NEEDED_REASON",
              NEW."IS_INFORMATION_UPDATE_NEEDED",
              NEW."SENIORITY_EFFECTIVE_DATE",
              NEW."IS_SENIORITY_OVERRIDDEN",
              NEW."SENIORITY_OVERRIDE_REASON",
              NEW."NUMBER_IN_BLOCK",
              NEW."DB_CREATE_TIMESTAMP",
              NEW."DB_CREATE_USER_ID",
              NEW."DB_LAST_UPDATE_TIMESTAMP",
              NEW."DB_LAST_UPDATE_USER_ID",
              NEW."APP_CREATE_TIMESTAMP",
              NEW."APP_CREATE_USERID",
              NEW."APP_CREATE_USER_GUID",
              NEW."APP_CREATE_USER_DIRECTORY",
              NEW."APP_LAST_UPDATE_TIMESTAMP",
              NEW."APP_LAST_UPDATE_USERID",
              NEW."APP_LAST_UPDATE_USER_GUID",
              NEW."APP_LAST_UPDATE_USER_DIRECTORY",
			  NEW."TYPE",
			  NEW."STATUS_COMMENT",
			  NEW."LEGAL_CAPACITY",
			  NEW."LICENCED_GVW",
			  NEW."PUP_LEGAL_CAPACITY",
              NEW."CONCURRENCY_CONTROL_NUMBER"
             );
             RETURN NEW;
        ELSIF (TG_OP = 'UPDATE') THEN
        	---- First update the previously active row
            UPDATE public."HET_EQUIPMENT_HIST" eqphis
            SET "END_DATE" = l_current_timestamp
            WHERE eqphis."EQUIPMENT_ID" = NEW."EQUIPMENT_ID"
            AND eqphis."END_DATE" IS NULL;
            ---- Now insert the new current row
        	INSERT INTO public."HET_EQUIPMENT_HIST"
            ("EQUIPMENT_HIST_ID",
             "EQUIPMENT_ID",
             "EFFECTIVE_DATE",
             "END_DATE",
             "APPROVED_DATE",
             "ARCHIVE_DATE",
             "ARCHIVE_REASON",
             "BLOCK_NUMBER",
             "ARCHIVE_CODE",
             "DISTRICT_EQUIPMENT_TYPE_ID",
             "EQUIPMENT_CODE",
             "LOCAL_AREA_ID",
             "MAKE",
             "MODEL",
             "OPERATOR",
             "OWNER_ID",
             "PAY_RATE",
             "RECEIVED_DATE",
             "REFUSE_RATE",
             "LICENCE_PLATE",
             "SENIORITY",
             "SERIAL_NUMBER",
             "SIZE",
             "STATUS",
             "TO_DATE",
             "YEARS_OF_SERVICE",
             "SERVICE_HOURS_LAST_YEAR",
             "SERVICE_HOURS_THREE_YEARS_AGO",
             "SERVICE_HOURS_TWO_YEARS_AGO",
             "YEAR",
             "LAST_VERIFIED_DATE",
             "INFORMATION_UPDATE_NEEDED_REASON",
             "IS_INFORMATION_UPDATE_NEEDED",
             "SENIORITY_EFFECTIVE_DATE",
             "IS_SENIORITY_OVERRIDDEN",
             "SENIORITY_OVERRIDE_REASON",
             "NUMBER_IN_BLOCK",
             "DB_CREATE_TIMESTAMP",
             "DB_CREATE_USER_ID",
             "DB_LAST_UPDATE_TIMESTAMP",
             "DB_LAST_UPDATE_USER_ID",
             "APP_CREATE_TIMESTAMP",
             "APP_CREATE_USERID",
             "APP_CREATE_USER_GUID",
             "APP_CREATE_USER_DIRECTORY",
             "APP_LAST_UPDATE_TIMESTAMP",
             "APP_LAST_UPDATE_USERID",
             "APP_LAST_UPDATE_USER_GUID",
             "APP_LAST_UPDATE_USER_DIRECTORY",
			 "TYPE",
			 "STATUS_COMMENT",
			 "LEGAL_CAPACITY",
			 "LICENCED_GVW",
			 "PUP_LEGAL_CAPACITY",
             "CONCURRENCY_CONTROL_NUMBER"
            )
            VALUES( 
              nextval('"HET_EQUIPMENT_HIST_ID_seq"'::regclass),
              NEW."EQUIPMENT_ID",
              l_current_timestamp,
              NULL,
              NEW."APPROVED_DATE",
              NEW."ARCHIVE_DATE",
              NEW."ARCHIVE_REASON",
              NEW."BLOCK_NUMBER",
              NEW."ARCHIVE_CODE",
              NEW."DISTRICT_EQUIPMENT_TYPE_ID",
              NEW."EQUIPMENT_CODE",
              NEW."LOCAL_AREA_ID",
              NEW."MAKE",
              NEW."MODEL",
              NEW."OPERATOR",
              NEW."OWNER_ID",
              NEW."PAY_RATE",
              NEW."RECEIVED_DATE",
              NEW."REFUSE_RATE",
              NEW."LICENCE_PLATE",
              NEW."SENIORITY",
              NEW."SERIAL_NUMBER",
              NEW."SIZE",
              NEW."STATUS",
              NEW."TO_DATE",
              NEW."YEARS_OF_SERVICE",
              NEW."SERVICE_HOURS_LAST_YEAR",
              NEW."SERVICE_HOURS_THREE_YEARS_AGO",
              NEW."SERVICE_HOURS_TWO_YEARS_AGO",
              NEW."YEAR",
              NEW."LAST_VERIFIED_DATE",
              NEW."INFORMATION_UPDATE_NEEDED_REASON",
              NEW."IS_INFORMATION_UPDATE_NEEDED",
              NEW."SENIORITY_EFFECTIVE_DATE",
              NEW."IS_SENIORITY_OVERRIDDEN",
              NEW."SENIORITY_OVERRIDE_REASON",
              NEW."NUMBER_IN_BLOCK",
              NEW."DB_CREATE_TIMESTAMP",
              NEW."DB_CREATE_USER_ID",
              NEW."DB_LAST_UPDATE_TIMESTAMP",
              NEW."DB_LAST_UPDATE_USER_ID",
              NEW."APP_CREATE_TIMESTAMP",
              NEW."APP_CREATE_USERID",
              NEW."APP_CREATE_USER_GUID",
              NEW."APP_CREATE_USER_DIRECTORY",
              NEW."APP_LAST_UPDATE_TIMESTAMP",
              NEW."APP_LAST_UPDATE_USERID",
              NEW."APP_LAST_UPDATE_USER_GUID",
              NEW."APP_LAST_UPDATE_USER_DIRECTORY",
			  NEW."TYPE",
			  NEW."STATUS_COMMENT",
			  NEW."LEGAL_CAPACITY",
			  NEW."LICENCED_GVW",
			  NEW."PUP_LEGAL_CAPACITY",
              NEW."CONCURRENCY_CONTROL_NUMBER"
             );
     	RETURN NEW;
        ELSIF (TG_OP = 'DELETE') THEN
        	---- First update the previously active row
            UPDATE public."HET_EQUIPMENT_HIST" eqphis
            SET "END_DATE" = l_current_timestamp
            WHERE eqphis."EQUIPMENT_ID" = OLD."EQUIPMENT_ID"
            AND eqphis."END_DATE" IS NULL;
            RETURN NEW;
    END IF;
    RETURN NULL;
   	END;

$BODY$;

ALTER FUNCTION public.het_eqp_ar_iud_tr()
    OWNER TO "user6DA";
