node('bddstack') {

	stage('Automated FT') {
		//the checkout is mandatory, otherwise functional test would fail
        echo "checking out source"
        echo "Build: ${BUILD_ID}"
        checkout scm
        dir('functional-tests') {
            try {
                sh 'export TEST_USERNAME=${TEST_USERNAME}\nexport TEST_PASSWORD=${TEST_PASSWORD}\n./gradlew --debug --stacktrace chromeHeadlessTest'
                } finally {
                            archiveArtifacts allowEmptyArchive: true, artifacts: 'build/reports/**/*'
                            archiveArtifacts allowEmptyArchive: true, artifacts: 'build/test-results/**/*'
                            junit 'build/test-results/**/*.xml'
                            publishHTML (target: [
                                        allowMissing: false,
                                        alwaysLinkToLastBuild: false,
                                        keepAll: true,
                                        reportDir: 'build/reports/spock',
                                        reportFiles: 'index.html',
                                        reportName: "BDD Spock Report"
                                    ])
                            publishHTML (target: [
                                        allowMissing: false,
                                        alwaysLinkToLastBuild: false,
                                        keepAll: true,
                                        reportDir: 'build/reports/tests/chromeHeadlessTest',
                                        reportFiles: 'index.html',
                                        reportName: "Full Test Report"
                                    ])        
                    }
        }
    }
}
