apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: v1
    stringData:
      SERVICE_USER: ${SERVICE_USER}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}
    kind: Secret
    metadata:
      name: service-account
    type: Opaque
parameters:
  - description: Service Account User Name
    displayName: SERVICE_USER
    name: SERVICE_USER
    required: true
    value: ""
  - description: Service Account User Password
    displayName: SERVICE_PASSWORD
    name: SERVICE_PASSWORD
    required: true
    value: ""
