CREATE TABLE public."HET_ROLLOVER_PROGRESS"
(
  "DISTRICT_ID" integer,
  "PROGRESS_PERCENTAGE" integer
);

ALTER TABLE ONLY public."HET_ROLLOVER_PROGRESS"
ADD CONSTRAINT "PK_HET_ROLLOVER_PROGRESS" PRIMARY KEY
("DISTRICT_ID");

ALTER TABLE ONLY public."HET_ROLLOVER_PROGRESS"
ADD CONSTRAINT "FK_HET_ROLLOVER_PROGRESS_DISTRICT_ID" FOREIGN KEY
("DISTRICT_ID") REFERENCES public."HET_DISTRICT"
("DISTRICT_ID");

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public."HET_ROLLOVER_PROGRESS" TO het_application_proxy;

DROP TABLE public."HET_PERSON";

DROP TABLE public."HET_LOCAL_AREA_ROTATION_LIST";

DROP TABLE public."HET_IMPORT_MAP";

ALTER TABLE public."HET_DISTRICT_STATUS" ADD CONSTRAINT "PK_HET_DISTRICT_STATUS" PRIMARY KEY ("DISTRICT_ID");