CREATE TABLE public."HET_ROLLOVER_PROGRESS"
(
  "DISTRICT_ID" integer,
  "PROGRESS_PERCENTAGE" integer
);

CREATE UNIQUE INDEX "HET_ROLLOVER_PROGRESS_UK" ON public."HET_ROLLOVER_PROGRESS"
("DISTRICT_ID") TABLESPACE pg_default;

ALTER TABLE "HET_ROLLOVER_PROGRESS" ADD CONSTRAINT "HET_ROLLOVER_PROGRESS_UK" UNIQUE
USING INDEX "HET_ROLLOVER_PROGRESS_UK";

ALTER TABLE ONLY public."HET_ROLLOVER_PROGRESS"
ADD CONSTRAINT "FK_HET_ROLLOVER_PROGRESS_DISTRICT_ID" FOREIGN KEY
("DISTRICT_ID") REFERENCES public."HET_DISTRICT"
("DISTRICT_ID");

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public."HET_ROLLOVER_PROGRESS" TO het_application_proxy;
