INSERT INTO "HET_PERMISSION"
("PERMISSION_ID", "CODE", "NAME", "DESCRIPTION", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_PERMISSION_ID_seq"'::regclass), 'WriteAccess', 'Write Access', 'Permission to add, update, delete records', 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_PERMISSION" WHERE "CODE" = 'WriteAccess');

INSERT INTO "HET_ROLE"
("ROLE_ID", "NAME", "DESCRIPTION", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_ID_seq"'::regclass), '6-HETS Read Only User', 'Read Only Access to the Whole System', 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE" WHERE "NAME" = '6-HETS Read Only User');

WITH wap AS (SELECT "PERMISSION_ID" AS id FROM "HET_PERMISSION" WHERE  "CODE" = 'WriteAccess')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT id FROM wap), 1, 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT id FROM wap) AND "ROLE_ID" = 1);

WITH wap AS (SELECT "PERMISSION_ID" AS id FROM "HET_PERMISSION" WHERE  "CODE" = 'WriteAccess')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT id FROM wap), 3, 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT id FROM wap) AND "ROLE_ID" = 3);

WITH wap AS (SELECT "PERMISSION_ID" AS id FROM "HET_PERMISSION" WHERE  "CODE" = 'WriteAccess')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT id FROM wap), 4, 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT id FROM wap) AND "ROLE_ID" = 4);

WITH wap AS (SELECT "PERMISSION_ID" AS id FROM "HET_PERMISSION" WHERE  "CODE" = 'WriteAccess')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT id FROM wap), 5, 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT id FROM wap) AND "ROLE_ID" = 5);

WITH wap AS (SELECT "PERMISSION_ID" AS id FROM "HET_PERMISSION" WHERE  "CODE" = 'WriteAccess')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT id FROM wap), 6, 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT id FROM wap) AND "ROLE_ID" = 6);

WITH 
wap AS (SELECT "PERMISSION_ID" AS pid FROM "HET_PERMISSION" WHERE  "CODE" = 'Login'),
ror AS (SELECT "ROLE_ID" AS rid FROM "HET_ROLE" WHERE  "NAME" LIKE '%Read Only User%')
INSERT INTO "HET_ROLE_PERMISSION"
("ROLE_PERMISSION_ID", "PERMISSION_ID", "ROLE_ID", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_PERMISSION_ID_seq"'::regclass), (SELECT pid FROM wap), (SELECT rid FROM ror), 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE_PERMISSION" WHERE "PERMISSION_ID" = (SELECT pid FROM wap) AND "ROLE_ID" = (SELECT rid FROM ror));