UPDATE "HET_EQUIPMENT_TYPE" 
SET "CONCURRENCY_CONTROL_NUMBER" = "CONCURRENCY_CONTROL_NUMBER" + 1,
    "NAME" = 'TRAILER/SKID MOUNTED BRUSHED CHIPPERS'
WHERE "NAME" = 'TRAILER/SKID MOUNTED';

UPDATE "HET_EQUIPMENT_TYPE" 
SET "CONCURRENCY_CONTROL_NUMBER" = "CONCURRENCY_CONTROL_NUMBER" + 1,
    "NAME" = 'ATV SNOW AND MUSKEG TRANSPORT'
WHERE "NAME" = 'SNOW AND MUSKEG TRANSPORT';

UPDATE "HET_EQUIPMENT_TYPE" 
SET "CONCURRENCY_CONTROL_NUMBER" = "CONCURRENCY_CONTROL_NUMBER" + 1,
    "NAME" = 'FELLER BUNCHERS'
WHERE "NAME" = 'FELLER BUNCHER';

UPDATE "HET_EQUIPMENT_TYPE" 
SET "CONCURRENCY_CONTROL_NUMBER" = "CONCURRENCY_CONTROL_NUMBER" + 1,
    "NAME" = 'SKIDDERS - TRACK'
WHERE "NAME" = 'SKIDDERS';