INSERT INTO "HET_PERMISSION"
("PERMISSION_ID", "CODE", "NAME", "DESCRIPTION", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_PERMISSION_ID_seq"'::regclass), 'WriteAccess', 'Write Access', 'Permission to add, update, delete records', 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_PERMISSION" WHERE "CODE" = 'WriteAccess');

INSERT INTO "HET_ROLE"
("ROLE_ID", "NAME", "DESCRIPTION", "APP_CREATE_USERID", "APP_CREATE_TIMESTAMP", "APP_LAST_UPDATE_USERID", "APP_LAST_UPDATE_TIMESTAMP", "DB_CREATE_TIMESTAMP", "DB_LAST_UPDATE_TIMESTAMP", "DB_LAST_UPDATE_USER_ID")
SELECT nextval('"HET_ROLE_ID_seq"'::regclass), '6-HETS Read Only User', 'Read Only Access to the Whole System', 'HETS', NOW(), 'HETS', NOW(), NOW(), NOW(), 'postgres'
WHERE NOT EXISTS (SELECT 1 FROM "HET_ROLE" WHERE "NAME" = '6-HETS Read Only User');
