#$/bin/bash
export MSYS_NO_PATHCONV=1

# ==============================================================================
# Script for loading test data into the TheOrgBook database
#
# * Requires curl
# ------------------------------------------------------------------------------
# Usage on Windows (using Git Bash):
#  ./load-all.sh <server URL>
#
# Example:
#  ./load-all.sh dev
#  ./load-all.sh http://localhost:60381
# ------------------------------------------------------------------------------
exitOnError () {
  rtnCd=$?
  if [ ${rtnCd} -ne 0 ]; then
	echo "An error has occurred while loading data!  Please check the previous output message(s) for details."
    exit ${rtnCd}
  fi
}
# ------------------------------------------------------------------------------
API_PREFIX=api
BULK_PATH=bulk
# ==============================================================================

if [ -z "${1}" ]; then
  echo Incorrect syntax
  echo USAGE ${0} "<server URL>"
  echo Example: ${0} dev
  echo "Where <server URL> is one of dev, test, prod or a full URL"
  exit
fi

# Before starting, remove the cookie authentication file.
# The ./load.sh script will add it if needed for the remainder of the calls
if [ -e cookie ]; then
  rm cookie
fi

# Generated by: "ls */*.json" and then set to a variable via regex
# Replace this section with the ls text, highlight it and regex replace
# In atom find: ^(.*)/ and replace: $1=$1/
service_areas=ServiceAreas/ServiceAreas_ServiceArea.json
local_areas=LocalAreas/LocalAreas_LocalArea.json
lookup_lists=LookupLists/LookupLists_LookupLists.json
equipment_types=EquipmentTypes/EquipmentTypes_EquipmentType.json
district_equipment_types=DistrictEquipmentTypes/DistrictEquipmentTypes_DistrictEquipmentType.json
contacts=Contacts/Contacts_Contact.json
projects=Project/Project_Project.json
owners=Owners/Owners_Owner.json
equipment=Equipment/Equipment_Equipment.json
rental_requests=RentalRequest/RentalRequest_RentalRequest.json

# ==============================================================================================
# The order of the loading is important - need to add independent files before dependent ones
# ==============================================================================================

# Users, Roles, and Permissions ...
./load.sh ./${service_areas} ${API_PREFIX}/serviceareas/${BULK_PATH} "$@"
exitOnError
./load.sh ./${local_areas} ${API_PREFIX}/localareas/${BULK_PATH} "$@"
exitOnError
./load.sh ./${lookup_lists} ${API_PREFIX}/lookuplists/${BULK_PATH} "$@"
exitOnError
./load.sh ./${equipment_types} ${API_PREFIX}/equipmenttypes/${BULK_PATH} "$@"
exitOnError
./load.sh ./${district_equipment_types} ${API_PREFIX}/districtequipmenttypes/${BULK_PATH} "$@"
exitOnError
./load.sh ./${contacts} ${API_PREFIX}/contacts/${BULK_PATH} "$@"
exitOnError
./load.sh ./${projects} ${API_PREFIX}/projects/${BULK_PATH} "$@"
exitOnError
./load.sh ./${owners} ${API_PREFIX}/owners/${BULK_PATH} "$@"
exitOnError
./load.sh ./${equipment} ${API_PREFIX}/equipment/${BULK_PATH} "$@"
exitOnError
./load.sh ./${rental_requests} ${API_PREFIX}/rentalrequests/${BULK_PATH} "$@"
exitOnError
