<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<Description>Common data code for the HETS application</Description>
    <Copyright>Copyright© 2017, Province of British Columbia</Copyright>
    <AssemblyTitle>Hets Data</AssemblyTitle>
    <AssemblyName>HetsData</AssemblyName>	
    <PackageId>HetsData</PackageId>	
    <Version>1.9.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Hangfire.Console" Version="1.4.3" />
    <PackageReference Include="Hangfire.Core" Version="1.8.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.29" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HetsCommon\HetsCommon.csproj" />
  </ItemGroup>

</Project>
