// API Requests
export const REQUESTS_BEGIN = 'REQUESTS_BEGIN';
export const REQUESTS_END = 'REQUESTS_END';
export const REQUESTS_ERROR = 'REQUESTS_ERROR';

// UI
export const UPDATE_EQUIPMENT_LIST_UI = 'UPDATE_EQUIPMENT_LIST_UI';
export const UPDATE_PHYSICAL_ATTACHMENTS_UI = 'UPDATE_PHYSICAL_ATTACHMENTS_UI';
export const UPDATE_OWNERS_UI = 'UPDATE_OWNERS_UI';
export const UPDATE_OWNER_CONTACTS_UI = 'UPDATE_OWNER_CONTACTS_UI';
export const UPDATE_OWNER_EQUIPMENT_UI = 'UPDATE_OWNER_EQUIPMENT_UI';
export const UPDATE_USERS_UI = 'UPDATE_USERS_UI';
export const UPDATE_PROJECTS_UI = 'UPDATE_PROJECTS_UI';
export const UPDATE_PROJECT_CONTACTS_UI = 'UPDATE_PROJECT_CONTACTS_UI';
export const UPDATE_RENTAL_REQUESTS_UI = 'UPDATE_RENTAL_REQUESTS_UI';

// Lookups
export const UPDATE_CITIES_LOOKUP = 'UPDATE_CITIES';
export const UPDATE_DISTRICTS_LOOKUP = 'UPDATE_DISTRICTS';
export const UPDATE_REGIONS_LOOKUP = 'UPDATE_REGIONS';
export const UPDATE_SERVICE_AREAS_LOOKUP = 'UPDATE_SERVICE_AREAS';
export const UPDATE_LOCAL_AREAS_LOOKUP = 'UPDATE_LOCAL_AREAS';
export const UPDATE_OWNERS_LOOKUP = 'UPDATE_OWNERS_LOOKUP';
export const UPDATE_EQUIPMENT_TYPES_LOOKUP = 'UPDATE_EQUIPMENT_TYPES_LOOKUP';

// Current User
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';

// Users
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USER = 'UPDATE_USER';

// Favourites
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';

// Equipment
export const UPDATE_EQUIPMENT_LIST_SEARCH = 'UPDATE_EQUIPMENT_LIST_SEARCH';
export const UPDATE_EQUIPMENT_LIST = 'UPDATE_EQUIPMENT_LIST';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';

// Owners
export const UPDATE_OWNERS_SEARCH = 'UPDATE_OWNERS_SEARCH';
export const UPDATE_OWNERS = 'UPDATE_OWNERS';
export const UPDATE_OWNER = 'UPDATE_OWNER';

// Projects
export const UPDATE_PROJECTS_SEARCH = 'UPDATE_PROJECTS_SEARCH';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';

// Rental Requests
export const UPDATE_RENTAL_REQUESTS_SEARCH = 'UPDATE_RENTAL_REQUESTS_SEARCH';
export const UPDATE_RENTAL_REQUESTS = 'UPDATE_RENTAL_REQUESTS';
export const UPDATE_RENTAL_REQUEST = 'UPDATE_RENTAL_REQUEST';

// Version
export const UPDATE_VERSION = 'UPDATE_VERSION';
