kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${PROJECT_NAME}
  creationTimestamp:
labels:
  template: api-build
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      # name: dotnet-50-rhel8
      name: dotnet-70
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            # name: registry.redhat.io/rhel8/dotnet-50:5.0-4
            name: registry.redhat.io/rhel8/dotnet-70:7.0-18
          # name: "5.0"
          name: "7.0"
          referencePolicy:
            type: Local
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: postgresql-10-rhel8
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: registry.redhat.io/rhel8/postgresql-10
          name: "1"
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
        labels:
          shared: "true"
        name: "${NAME}"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      creationTimestamp: null
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
        #   cpu: 2
        #   memory: 4Gi
        # requests:
        #   cpu: 1
        #   memory: 2Gi
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: "${DOTNET_STARTUP_PROJECT}"
          from:
            kind: ImageStreamTag
            # name: "dotnet-50-rhel8:5.0"
            name: "dotnet-70:7.0"
parameters:
  - description: Name of the project (HETS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "het"
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: api
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: "1.9.3"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ""
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: "master"
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: 'Server'
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
      DockerImage.
    required: true
    value: DockerImage
  - name: DOTNET_STARTUP_PROJECT
    displayName: DotNet Startup Project
    description: The path to the startup project for the .Net application.
    required: true
    value: HetsApi/HetsApi.csproj