apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: moti-cicd
objects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
      labels:
        app: ${NAME}
    rules:
      - apiGroups:
          - apps.openshift.io
          - ""
        resources:
          - deploymentconfigs
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - image.openshift.io
          - ""
        resources:
          - imagestreams
          - imagestreamtags
          - imagetags
          - imagestreamimages
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - buildconfigs/instantiate
        verbs:
          - create
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - builds/log
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - build.openshift.io
          - ""
        resources:
          - buildconfigs
          - builds
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - route.openshift.io
          - ""
        resources:
          - routes
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - route.openshift.io
          - ""
        resources:
          - routes/custom-host
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
          - endpoints
          - persistentvolumeclaims
          - replicationcontrollers
          - replicationcontrollers/scale
          - secrets
          - serviceaccounts
          - services
          - services/proxy
        verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
      - apiGroups:
          - template.openshift.io
          - ""
        resources:
          - processedtemplates
          - templateconfigs
          - templateinstances
          - templates
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
      labels:
        app: ${NAME}
    subjects:
      - kind: ServiceAccount
        name: ${NAME}
        namespace: ${PROJECT}-tools
    roleRef:
      kind: Role
      name: ${NAME}
      apiGroup: rbac.authorization.k8s.io
parameters:
  - displayName: Credentials Name
    description: |
      The name used for all components of the 
      credentials.
    name: NAME
    required: true
    value: moti-cicd
  - displayName: Namespace
    description: |
      The namespace where all of components of the
      credentials are stored.
    name: NAMESPACE
    required: true
  - displayName: Project
    decription: Project
    name: PROJECT
    required: true
